name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *' # Menjalankan setiap hari pada pukul 00:00 UTC
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update File (Opsional)
        run: |
          echo "Last updated on $(date)" > update.txt
          git add update.txt

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit -m "Auto update $(date)"
          git push
